### ISSUE TITLE
Some Regions and Provinces Don't Convert to Greek Cultures

### ISSUE THREAD

**Issue by DovahFett** [C1CK/Beyond-Typus-Cultural-Influence#14]
Greetings.  I just finished a playthrough with the Byzantine Resurgence mod and I noticed a few issue with the culture events.  I know your mod interacts pretty heavily with that one so I'm not sure if the issue is with it, or this.  

Anyways, what I noticed is that Sardinia and Corsica never get events to convert to a Greek assimilated culture.  Neither does Ireland, the Baleares, Madagascar, the Japan region, Borneo, the island of Jeju off Korea, Iceland, the Northern Isles area, the Philippines, Celebes, the sole Lazuri province in the East Pontus, the Mexico and Central America regions, and the Macaronesia islands off the coast of Morocco.  I also noticed that a few provinces in Georgia and Azerbaijan never converted for some reason.  Also, the province of Treberon near the Rhine is converted to the Galatikos culture when all of the other provinces around it convert to Belgikos.  I believe one of the missions converts it, after which it's never changed by an event to match the surrounding provinces.

I ran with the 0.0x MTTH multiplier for a while to see if any of the events would fire but they did not.

**Comment by Illuminati4628** [comment]
I've kinda not been looking at this so apologies for the long wait, just to confirm this was with the github mirror workshop item, correct? I went through the Hellenic stuff a while back and fixed up many of these issues, though islands not converting is an oversight for passive settlement, for now you'd have to jump start it with the regular settlement features, though honestly it kind of makes sense for islands.

I also didn't look too much into new world/colonial stuff as BYZ is not really expected to actually go colonial, in any case the image on the github mirror for Hellenic is all from natural events with the 0x modifier and a 5 dev jump start in the case of islands. The Lazuri culture not converting is probably because you have it accepted from the mission tree, accepted cultures do not convert under any circumstances unless you are an ai.

Brother cultures not converting was something I noticed but I made sure to change that, maybe I missed the Belgikos event. All in all the update to BT14 will be high priority at this point so getting these bugs fixed may take a bit, unless of course they already were.

**Comment by DovahFett** [comment]
Yes, I was using the GitHub mirror workshop item titled "[BETA] BT Addon : Cultural Influence | Github Mirror".  

To be honest I'm a little fuzzy on the details of that campaign beyond what I already posted in my initial report due to how long it's been since then.  But I do remember a few tidbits, like the Mediterranean islands (Corsica and Sardinia) not converting until I had manually converted one of their provinces to the main Greek culture.  That then jump-started the events to convert the rest.  It seems that they needed to physically border a province of my culture first, as I'm fairly certain that I had already given them enough development, though the mean time for the event could have been unusually high for some reason and coincidentally coincided with my manual conversions finishing.  Either way, I don't mind having to manually jump-start the process if that's the case, but I'd prefer if it said so somewhere, as a lot of the Greek settlement content is passive, so when I see something that is not my first instinct is to assume that something has gone wrong.

As for accepting cultures, you may be right in that I forgot to "un-accept" some of them, especially the ones that are accepted by missions.  That might also be why the Galatikos province didn't reconvert to match the cultures around it after the mission manually converted it.

The others ones though, like the missing provinces in the Caucasus region, I cannot offer alternate explanations for.  Their cultures were not accepted, I had activated the passive settlement option, all the provinces around them of the same original cultures did convert, and the event mean time was set to 0.0.  I eventually had to just convert them manually.

I wish I could give you more details but I no longer have the save from that campaign to reference.

**Comment by Illuminati4628** [comment]
I know why those provinces in Caucasia weren't converting, it was because their dev was too low, as the code was copied from the Arabic assimilation ones which has a line designed to prevent low dev sahara provinces from converting. For Armenian assimilation that didn't make much sense and I've removed it. For islands and stuff like that I've added a new line that will allow languages to jump from neighbouring sea tiles (much like how you can create claims from across them) to the passive settlement option. So this should all be fine in the next version when I release it.
